[tool.poetry]
name = "kyopro"
version = "0.1.0"
description = ""
authors = ["wakabame"]

[tool.poetry.dependencies]
python = "3.8.1"

[tool.poetry.dev-dependencies]
black = "^21.5b1"
flake8 = "^3.9.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
